controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

app_acceuil:
    path: /
    controller: App\Controller\Acceuil::number

app_logout:
    path: /logout
    methods: GET